// ==========================================================================
// CS2 Autoexec — Instance %%INSTANCE_NUM%%
// Generated by cs2-server-setup-script
// This file runs on server start before server.cfg
// ==========================================================================

// Add any commands that need to run before server.cfg here
