// ==========================================================================
// CS2 Server Configuration — Instance %%INSTANCE_NUM%%
// Generated by cs2-server-setup-script
// ESL Pro Tour 2026 competitive defaults (Section 2.4)
// ==========================================================================

// ---------------------------------------------------------------------------
// Server Identity
// ---------------------------------------------------------------------------
sv_hostname "%%HOSTNAME%%"
sv_setsteamaccount "%%GSLT_TOKEN%%"
sv_password "%%SERVER_PASSWORD%%"

// ---------------------------------------------------------------------------
// Network
// ---------------------------------------------------------------------------
sv_lan 0
sv_maxrate 0
sv_minrate 128000
sv_maxcmdrate 128
sv_mincmdrate 128

// ---------------------------------------------------------------------------
// RCON
// ---------------------------------------------------------------------------
rcon_password "%%RCON_PASSWORD%%"

// ---------------------------------------------------------------------------
// Logging (for eBot integration)
// ---------------------------------------------------------------------------
log on
sv_logflush 1
sv_logfile 1
mp_logdetail 3
mp_logmoney 1

// Log forwarding to eBot logs-receiver
logaddress_add_http "%%EBOT_LOG_ADDRESS%%/%%PUBLIC_IP%%:%%GAME_PORT%%"

// ---------------------------------------------------------------------------
// GOTV
// ---------------------------------------------------------------------------
tv_enable %%GOTV_ENABLED%%
tv_name "GOTV - %%HOSTNAME%%"
tv_title "%%HOSTNAME%%"
tv_port %%GOTV_PORT%%
tv_maxclients 32
tv_maxrate 0
tv_delay 30
tv_delaymapchange 1

// ---------------------------------------------------------------------------
// ESL Pro Tour 2026 Match Settings (Section 2.4)
// ---------------------------------------------------------------------------
mp_maxrounds 24
mp_roundtime 1.92
mp_startmoney 800
mp_freezetime 20
mp_buytime 20
mp_c4timer 40
mp_overtime_maxrounds 6
mp_overtime_startmoney 12500
mp_round_restart_delay 5
mp_items_prohibited ""

// ---------------------------------------------------------------------------
// Team / Gameplay
// ---------------------------------------------------------------------------
mp_autoteambalance 0
mp_limitteams 0
mp_friendlyfire 1
mp_overtime_enable 1
sv_alltalk 0
sv_deadtalk 0
